#!/usr/bin/perl

print "Content-type: text/html\n\n";

my ($num1, $num2) = split(' ', <STDIN>);

chomp($num1);
chomp($num2);

if(defined $num1 && defined $num2) {
    my $product = $num1 * $num2;
    print "The product of $num1 and $num2 is $product.";
} else {
    print "Please provide two numbers for multiplication.";
}